#!/bin/bash -e

gen_secret() {
	export SECRET=$(python -c "import base64; import uuid; print base64.b64encode(uuid.uuid4().bytes + uuid.uuid4().bytes)")
}

# Regen SickRage secrets
CONF=/etc/sickrage/config.ini
gen_secret
sed -i "/encryption_secret/ s|=.*|= $SECRET|" $CONF
gen_secret
sed =i "/web_cookie_secret/ s|=.*|= $SECRET|" $CONF
unset SECRET
